import type { Metadata } from "next";
import { Happy_Monkey } from "next/font/google";
import "./globals.css";

const happyMonkey = Happy_Monkey({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "400"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${happyMonkey.variable}`}
      >
        {children}
      </body>
    </html>
  );
}